### ISSUE TITLE
About Loss value problem

### ISSUE THREAD

**Issue by Zhucunjuan** [wjun0830/QD-DETR#12]
Hello, when reproducing this code, I found that the loss values are somewhat strange. The loss values are generally large, and it seems that they are not converging. Especially, the value of loss_saliency exceeds 4, and the value of loss_label shows an increasing trend in 40 evaluations.  I would like to ask if you have encountered such a problem in your work, whether the loss values are normal, and why they are slightly large. I attach the  "eval.log.txt" file in my reproducing results as follows:
[eval.log.txt](https://github.com/wjun0830/QD-DETR/files/11554644/eval.log.txt)

**Comment by Zhucunjuan** [comment]
Thank you very much for your quick reply！
I have another question, why are the saliency scores predicted during the validation process all very small negative numbers, such as -11, -8, -9. However, in the Moment Detr task, most of the predicted score values are positive.

**Comment by wjun0830** [comment]
Simply put, that is because we suppress the saliency scores when using rank contrastive loss and suppress the negative saliency value.
To make gaps between each score value, clips with lower GT saliency scores are suppressed multiple times in the rank contrastive loss.
Furthermore, if you see Eq. 2, the saliency scores for the negative pairs are suppressed with the log function which makes the score retain negative values.
In evaluation, saliency scores are used to rank the frame-wise highlightness and in this paper thus, not trained with a regression loss to yield GT scores.

**Comment by Zhucunjuan** [comment]
Thank you very much for your patient answer.
