### ISSUE TITLE
About saliency score

### ISSUE THREAD

**Issue by zay1817** [wjun0830/QD-DETR#41]
May I ask why the result of my training ”pred_saliency_scores“ is always negative?

**Comment by wjun0830** [comment]
We guess that is because the rank contrastive iteratively forces most of the samples to have lower values.
We thought that having negative values is not much a problem since highlight detection aims to capture the frames with relatively higher saliency scores. So normalizing the per instance value is an easy way to convert negatives into positive values.

**Comment by zay1817** [comment]
Thanks for your reply.
